import { z } from 'zod';

export const ERROR_CODES = [
  'invalid_message',
  'invalid_frame',
  'frame_too_large',
  'incompatible_protocol',
  'authentication_failed',
  'request_not_found',
  'request_cancelled',
  'session_not_found',
  'session_limit_reached',
  'session_not_ready',
  'session_interrupted',
  'stale_lease_epoch',
  'lease_unavailable',
  'lease_not_owned',
  'invalid_pty_transition',
  'invalid_shell_transition',
  'agent_task_conflict',
  'agent_task_limit_reached',
  'invalid_agent_task_transition',
  'invalid_agent_turn_transition',
  'invalid_tool_call_transition',
  'agent_loop_limit_reached',
  'command_transaction_conflict',
  'invalid_command_transaction_transition',
  'approval_required',
  'approval_invalid',
  'policy_denied',
  'interaction_required',
  'shell_lost',
  'command_protocol_error',
  'history_gap',
  'provider_unavailable',
  'provider_capability_missing',
  'provider_stream_error',
  'provider_validation_in_progress',
  'invalid_provider_validation_transition',
  'secret_store_error',
  'storage_error',
  'resource_exhausted',
  'shell_driver_unavailable',
  'local_path_outside_home',
  'local_file_conflict',
  'local_file_binary',
  'local_file_sensitive',
  'local_file_too_large',
  'plaintext_protocol_error',
  'command_not_auditable',
  'execution_environment_unverified',
  'internal_error',
] as const;

export const errorCodeSchema = z.enum(ERROR_CODES);

export const protocolErrorSchema = z.strictObject({
  code: errorCodeSchema,
  message: z.string().min(1),
  retryable: z.boolean(),
  details: z.record(z.string(), z.json()).optional(),
});

export type ErrorCode = z.infer<typeof errorCodeSchema>;
export type ProtocolError = z.infer<typeof protocolErrorSchema>;
