export const DESKTOP_IPC_REQUEST_CHANNELS = [
  'sessions:list',
  'sessions:environment',
  'sessions:create',
  'sessions:set-dialect',
  'sessions:close',
  'terminal:write',
  'terminal:resize',
  'terminal:replay',
  'resources:get',
  'resources:refresh',
  'agent:start',
  'agent:cancel',
  'agent:history',
  'agent:reset-conversation',
  'agent:interrupt',
  'agent:approve',
  'agent:takeover',
  'providers:list',
  'providers:save',
  'providers:discover-models',
  'providers:cancel-discovery',
  'providers:remove',
  'models:list',
  'models:save',
  'models:test',
  'models:set-enabled',
  'models:set-default',
  'models:remove',
  'models:import-discovered',
  'audit:list',
  'audit:cleanup',
  'core:status',
  'core:exit',
] as const;

export const DESKTOP_IPC_EVENT_CHANNELS = [
  'terminal:output',
  'agent:timeline',
  'session:resources',
  'session:changed',
] as const;

export type DesktopIpcEventChannel = (typeof DESKTOP_IPC_EVENT_CHANNELS)[number];
